band_name_list = [
'Arctic Monkeys',
'Alice In Chains',
'Alter Bridge',
'A Perfect Circle',
'Band Perry',
'Blur',
'Breaking Benjamin',
'Coldplay',
'Foo Fighters',
'Green Day',
'Hoobastank',
'Metalica',
'Muse',
'Mutemath',
'Oasis',
'Oceansize',
'One OK Rock',
'Pay Money To My Pain',
'Porcupinetree',
'Puddle Of Mudd',
'Radiohead',
'Red Hot Chili Peppers',
'Stereophonics',
'The Beatles',
'The Fray',
'The Strokes',
]